// Auto-generated by typescript_record_browser_flow from @playwright/mcp tool calls.
// Flow: home-navigation
// Dev server: http://localhost:4300
import { test, expect } from '@playwright/test';

test('home-navigation', async ({ page }) => {
  await page.goto('http://localhost:4300');
  await expect(page.getByText("Übersicht").first()).toBeVisible();
  await expect(page.getByText("Pläne").first()).toBeVisible();
  await expect(page.getByText("Gerichte").first()).toBeVisible();
  await expect(page.getByText("Einstellungen").first()).toBeVisible();
});
