ALTER TABLE dish ADD COLUMN carbs_grams DOUBLE PRECISION;
ALTER TABLE dish ADD COLUMN fat_grams DOUBLE PRECISION;
ALTER TABLE dish ADD COLUMN vitamin_a_mcg DOUBLE PRECISION;
ALTER TABLE dish ADD COLUMN vitamin_c_mg DOUBLE PRECISION;
ALTER TABLE dish ADD COLUMN vitamin_d_mcg DOUBLE PRECISION;

ALTER TABLE user_profile ADD COLUMN nutrition_tracking_enabled BOOLEAN NOT NULL DEFAULT FALSE;
